name: deploy

on:
  workflow_call:
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Check Env Vars
      uses: dworks-action/require-env-vars@v0
      with:
        vars: GCP_PROJECT_ID GCP_SA_KEY

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.7.0
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        service_account_key: ${{ env.GCP_SA_KEY }}
        export_default_credentials: true

    - name: 'Use gcloud CLI'
      run: |
        gcloud auth list --filter=status:ACTIVE --format="value(account)"

    - name: Deploy API image to Cloud Run
      run: |
        gcloud run deploy user-profiles-technical-api \
        --image gcr.io/${{ env.GCP_PROJECT_ID }}/api:${{ github.sha }} \
        --platform managed \
        --region europe-west4 \
        --set-secrets "PROJECT_NAME=PROJECT_NAME:latest" \
        --set-secrets "PROJECT_VERSION=PROJECT_VERSION:latest" \
        --set-secrets "NEXT_PUBLIC_API_HOST=NEXT_PUBLIC_API_HOST:latest" \
        --set-secrets "TURSO_DATABASE_URL=TURSO_DATABASE_URL:latest" \
        --set-secrets "TURSO_AUTH_TOKEN=TURSO_AUTH_TOKEN:latest" \
        --allow-unauthenticated

    - name: Deploy WEB image to Cloud Run
      run: |
        gcloud run deploy user-profiles-technical-web \
        --image gcr.io/${{ env.GCP_PROJECT_ID }}/web:${{ github.sha }} \
        --platform managed \
        --region europe-west4 \
        --set-secrets "PROJECT_NAME=PROJECT_NAME:latest" \
        --set-secrets "PROJECT_VERSION=PROJECT_VERSION:latest" \
        --set-secrets "NEXT_PUBLIC_API_HOST=NEXT_PUBLIC_API_HOST:latest" \
        --set-secrets "NEXT_PUBLIC_WEB_HOST=NEXT_PUBLIC_WEB_HOST:latest" \
        --set-secrets "NEXT_PUBLIC_GITHUB_USERNAME=NEXT_PUBLIC_GITHUB_USERNAME:latest" \
        --allow-unauthenticated
