name: dev
on:
  push:
    branches: [dev**]
    paths-ignore:
      - "**.md"
      - .vscode/**
  pull_request_target:
    types:
      - opened
      - synchronize
      - ready_for_review
    branches:
      - main
    paths-ignore:
      - "**.md"
      - .vscode/**

jobs:
  dev-test:
    timeout-minutes: 30
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install deps (ci only)
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Run lint
        run: npm run lint
        continue-on-error: true

      - name: Run unit tests
        run: npm run test
